### ISSUE TITLE
Server-check "problem"

### ISSUE THREAD

**Issue by CoolCanuck** [zonzorp/COMP1071#9]
line 700 of server-check.sh has "problem" but should be "problem-report" (like all other entries) 
Same issue on line  526, 545, 556, 567, 582,  640, 700, 773

Line 581 & 639 says "heirarchy" , but proper spelling is "hierarchy"

I am attempting to learn git. I apologize for the issue report. 

~Brayden

**Comment by kyle95wm** [comment]
@CoolCanuck I can put this into a PR if you want. I've worked with @zonzorp  with this script on many occasions. I'm a 2nd year CSTN student, so I know a lot about Bash

**Comment by CoolCanuck** [comment]
Holy cow. That was fast. I'm in class right now. So whatever you think is best. Non-urgent.

**Comment by kyle95wm** [comment]
@CoolCanuck I'm following this repo so I get notified whenevr someone posts ann issue/commit. I'll get this PR ready in like 10 minutes
